### ISSUE TITLE
error with perl library

### ISSUE THREAD

**Issue by fmotnaldo** [BaldMansMojo/check_vmware_esx#101]
Hi,

I wan tot use the plugin but the following error apear.

[root@nagios libexec]# ./check_vmware_esx.pl
Can't locate Time/Duration.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./check_vmware_esx.pl line 1238.
BEGIN failed--compilation aborted at ./check_vmware_esx.pl line 1238.
[root@nagios libexec]#

I isntelled the modules for red hat but the error persist. 

cpan -i Class::Time/Duration.pm

[root@nagios libexec]# yum provides '*/vendor_perl/DateTime.pm'
Loaded plugins: package_upload, product-id, security, subscription-manager
rhel-6-server-rpms                                                                                                                        | 2.1 kB     00:00
rhel-6-server-satellite-tools-6.1-rpms                                                                                                    | 2.1 kB     00:00
1:perl-DateTime-0.5300-2.el6.x86_64 : Date and time objects
Repo        : rhel-6-server-rpms
Matched from:
Filename    : /usr/lib64/perl5/vendor_perl/DateTime.pm

1:perl-DateTime-0.5300-2.el6.x86_64 : Date and time objects
Repo        : installed
Matched from:
Filename    : /usr/lib64/perl5/vendor_perl/DateTime.pm

[root@nagios libexec]#

**Comment by BaldMansMojo** [comment]
First: Don't install packages from CPAN. If you have tried it from CPAN and later on you install a RPM you will run into trouble. I'm using CentOS (Redhat Clone) 6.6 and use the following package from CentOS: perl-DateTime-0.5300-2.el6.x86_64 . I had never trouble with it.

If you have a new installation DON'T use SDK 6.x . It has some bugs and won't run sufficiently under RHEL/CentOS 6.x. Take the last 5.x . As long as I don't use new features from 6.x 5.x will work.

Give me a short note if it worx so I can close this issue.
Regards
Martin

**Comment by fmotnaldo** [comment]
Hi,

I remove the version 6 of SDK and install this
one VMware-vSphere-Perl-SDK-5.5.0-2043780.x86_64.tar.gz but the issue
persist.

[root@nagios libexec]# ./check_vmware_esx.pl -V
Can't locate Time/Duration.pm in @INC (@INC contains:
/usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl
/usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./
check_vmware_esx.pl line 1238.
BEGIN failed--compilation aborted at ./check_vmware_esx.pl line 1238.


Please let me if I nee to remove the CPAM libraries and reintall again CPAN
and perl time packages.

Regards

On Mon, Oct 17, 2016 at 4:17 PM, Martin Fuerstenau <notifications@github.com

**Comment by BaldMansMojo** [comment]
Replacing SDK 6 with SDK 5 had nothing to do with your problem. It was to avoid the next upcoming problems ;-))

If you have installed the RPM for datetime -> remove it.. The files for the manually installed datetime must be removed maually. As mentioned "Don't install software by hand from CPAN if there are RPMs available. This will cause trouble".

For the manually installed software determine which files has been installed and remove them.

cpan -i is quite stupid because there is no uninstall option.  So download the source from CPAN, do all the make but NOT the make install. Look wich files should be installed and remove this files from the system perl directories.

With the package installed correctly it should look like:

rpm -ql perl-DateTime-1.03-2.0.cf.rhel6.x86_64
/usr/lib64/perl5/vendor_perl/DateTime
/usr/lib64/perl5/vendor_perl/DateTime.pm
/usr/lib64/perl5/vendor_perl/DateTime/Duration.pm
/usr/lib64/perl5/vendor_perl/DateTime/Helpers.pm
/usr/lib64/perl5/vendor_perl/DateTime/Infinite.pm
/usr/lib64/perl5/vendor_perl/DateTime/LeapSecond.pm
/usr/lib64/perl5/vendor_perl/DateTimePP.pm
/usr/lib64/perl5/vendor_perl/DateTimePPExtra.pm
/usr/lib64/perl5/vendor_perl/auto/DateTime
/usr/lib64/perl5/vendor_perl/auto/DateTime/DateTime.so
/usr/share/doc/perl-DateTime-1.03
/usr/share/doc/perl-DateTime-1.03/CREDITS
/usr/share/doc/perl-DateTime-1.03/Changes
/usr/share/doc/perl-DateTime-1.03/LICENSE
/usr/share/doc/perl-DateTime-1.03/README
/usr/share/doc/perl-DateTime-1.03/TODO
/usr/share/man/man3/DateTime.3pm.gz
/usr/share/man/man3/DateTime::Duration.3pm.gz
/usr/share/man/man3/DateTime::Infinite.3pm.gz
/usr/share/man/man3/DateTime::LeapSecond.3pm.gz

You are the first one with this problem. 

Regards
Martin

**Comment by BaldMansMojo** [comment]
I will close it because I haven't heard anything more.

Martin
