### ISSUE TITLE
Storage health status unavailable on vsphere 6.5 hosts

### ISSUE THREAD

**Issue by 4b42** [BaldMansMojo/check_vmware_esx#102]
i updated 3 of my vsphere hosts from 6.0 to 6.5 and now i got the following message:

Warning: The session being saved to '/tmp/vsphere_​session' is expired or not authenticated.
UNKNOWN: Storage health status unavailable

i tried with admin permissions, but nothing changed.

**Comment by BaldMansMojo** [comment]
So I need a little bit more about your configuration.

- Which version of the SDK?
- Where have you configured the path /tmp/vsphere_​session ?

The last is interesting because I never save a session in a file named vsphere_​session.

Regards - Martin

**Comment by 4b42** [comment]
Oh no :(
Sorry, my mistake, i used SDK-6.0.0-2503617.x86_64, after upgrade to SDK-6.5.0-4566394.x86_64 the WARNING message was gone and Icinga can get the storage health.
_The vsohere was the hostname (/tmp/<HOSTNAME>_​session)._

Thank you:)

**Comment by BaldMansMojo** [comment]
If you look at some closed (and open) issues  you will see some problems with SDK 6.x. Because currently nothing of 6.x is used SDK 5.x is sufficient. SDK 6.x has several drwabacks. So it is nearly not possible to install it on RedHat/ CentOS 6.x using the needed Perl modules as packages. And there are other problems too.
Martin
