### ISSUE TITLE
Server version unavailable at ISSUE

### ISSUE THREAD

**Issue by talbaror** [BaldMansMojo/check_vmware_esx#105]
Hello,
Suddenly plugin don't work anymore i have following below error:
`Server version unavailable at 'https://<IP>:443/sdk/vimService.wsdl' at /usr/share/perl/5.22/VMware/VICommon.pm line 734.
`
Any idea , i saw that  below settigs should solve the issue but its already configured
Thanks

> # Prevent SSL certificate validation
> 
> $ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0;

**Comment by BaldMansMojo** [comment]
Hi,

this is not a plugin issue. It is an issue of the Vmware Perl SDK. Have you did an upgrade/update on your Nagios host? This issue may happen with the Perl LWP module not corresponding with the installed SDK. Because the SDK is not based on Linux package format (.deb,.rpm etc.) there is no dependency check for the SDK and the LWP. Which SDK version do you use? 
Regards - Martin

**Comment by tbaror** [comment]
Hi,
Thanks for the answer , its  	VMware vSphere Perl SDK 6.5

**Comment by BaldMansMojo** [comment]
If you look into the closed issues you will see that SDK 6.x is buggy. There is no need to use 6.x. Use 5.x. I just updated the the readme file. As long as I don't use features of SDK 6.x the older one will work fine.

**Comment by tbaror** [comment]
OK thanks , i will downgrade it to 5.x
Thanks again :) 👍

**Comment by xtruthx** [comment]
Hi. On a debian jessie 8.8 i run in the same problem. So the only solution was to downgrade the LWP Module.
I did that as follows:

Identify actuall version of the installed perl module lwp:
`cpan –D LWP`

Downgrade to version 5.837
`cd /usr/local/src
 wget http://search.cpan.org/CPAN/au…/libwww-perl-5.837.tar.gz
 tar -xzf libwww-perl-5.837.tar.gz
 cd libwww-perl-5.837/
 perl Makefile.PL
 make
 make test
 make install`

check again if you now on version 5.837:
`cpan –D LWP`

So that works fine for me i hope it helps.

**Comment by pseudoyams** [comment]
Hey Everyone-
 Im having the same "Server Version Unavailable" error.  Ive tried downgrading to the VMware SDK to v5.5 (we were on 6.5) and also downgrading LWP to 5.837, but the error persists after each (and both).

This problem arose for us when we rebuilt the vCenter server - from VCSA v6.5 to a fresh install - due to various reasons...we have a small-ish environment.  The checks were working perfectly before the new vCenter install.

Any other thoughts on how we may be able to correct this? Ive been searching for a day and trying any/all options without success.

Thanks much!

**Comment by anriKogan** [comment]
I have solved it it this way:
$sudo cpan
cpan[1] install GAAS/libwww-perl-5.837.tar.gz

$vmware-cmd --version
vSphere SDK for Perl version: 6.5.0
Script 'vmware-cmd' version: 6.5.0

After that I get vmware-cmd working without any "Server version unavailable" error.

**Comment by BaldMansMojo** [comment]
Wonderfull - thanks.
Martin
