### ISSUE TITLE
Issue monitoring ESx 6.5

### ISSUE THREAD

**Issue by tbaror** [BaldMansMojo/check_vmware_esx#108]
Hello,

I have issue with monitoring  Esx 6.5  with following below error , using Perl SDK 5.5
Please advise 
Thanks

```
Possible precedence issue with control flow operator at /usr/share/perl/5.22/VMware/VICommon.pm line 2147.
Warning: The session being saved to '/tmp/1x.x.x_session' is expired or not authenticated.
WARNING: 1 health issue(s) found in 139 checks: 1) [Warning] [Type: power] [Name: Power Supply 3 Power Supplies - Redundancy lost] [Label: Yellow] [Summary: Sensor is operating under conditions that are non-critical]
```

**Comment by dinasty02091994** [comment]
I see the same problem. 
If I update to Perl SDK 6.5 the warning dissapears but i still have problems with the task log being filled with login messages. 
Once i updated to Perl SDK 6.5 the same thing also started happening on my ESXi 5.5 hosts, this problem didn't exist when using the 5.5 SDK.

**Comment by BaldMansMojo** [comment]
As mentioned (often) earlier : SDK 6.x is buggy and currently not supported. There is normally no need for 6.x because currently no features of 6.x are used. I cant fit at the moment because we are just migrating to ESX 6.x. And I don't have the error. Remove the sessionfile and look what's written in it with the next run. There is a lot of installations outside running ESX 6.x fine with SDK 5.x. Someone put a pull request on GitHub for a fix. But this is nonsense because he set a check to "always true". I will try to install SDK 6.x on a test machine within the next weeks.

**Comment by markymarky92** [comment]
I had exactly the same error with some ESXi hosts on 6.5 versions. I've updated the SDK for Perl from 5.5 to 6.5 and the issue was resolved.

**Comment by peter-manton** [comment]
Can also confirm as @aharlaut mentioned upgrading the SDK to 6.5 seems to do the trick

**Comment by BaldMansMojo** [comment]
I merged all pull requests and have now system with SDK 6.5. So this should solve the problem.
