### ISSUE TITLE
Storage health status unavailable after upgrade to 6.5

### ISSUE THREAD

**Issue by mikenowak** [BaldMansMojo/check_vmware_esx#110]
Similar to #102 

I've just upgraded my HP Microserver Gen8 to ESXi 6.5 and the `-S runtime -s storagehealth` no longer works and I am now getting this:

UNKNOWN: Storage health status unavailable

Querying with `-S runtime -s health` returns the following - including Storage (14x) OK

OK: All 32 health checks are GREEN: other (11x), Memory (3x), Storage (14x), power (3x), CPU (1x)

I am running VMware-vSphere-Perl-SDK-5.5.0-2043780.x86_64 and temporary upgrading to VMware-vSphere-Perl-SDK-6.5.0-4566394.x86_64 didnt fix the problem but created a range of others :)

I also noticed that if I login to the vmware UI and navigate to Monitor ->  Hardware - now there are two tabs in there - Sensors (that includes storage health) and Storage that didn't exist in 6.0 (blank for me).

Could somebody who had upgraded to 6.5 send me some screenshots of what their Sensors/Storage tabs from the UI look like?

**Comment by bb-Ricardo** [comment]
We have similar issues.

Check this comment https://github.com/BaldMansMojo/check_vmware_esx/issues/130#issuecomment-419341567

The problem is the VMware support in ESXi 6.5 for HP hardware. The data returned from the CIM interface just doesn't contain all the hardware informations anymore. The same reason why you don't see anything in vCenter. It's probably better to check the server hardware via check_hpasm and the servers ILO interface.

**Comment by BaldMansMojo** [comment]
Yep. This is caused by the hardware agents. And I can process only the date I got from VMware. So I can do nothing.
