### ISSUE TITLE
i need help (nagios website:Can't locate Monitoring/Plugin/Functions.pm in @INC)

### ISSUE THREAD

**Issue by wangxd0206** [BaldMansMojo/check_vmware_esx#112]
display information in my centos 7 , 
[root@localhost libexec]# ./check_vmware_api.pl -H host-ip -u nagios -p Nb@* -l cpu 
CHECK_VMWARE_API.PL OK - cpu usage=589.00 MHz (6.90%) | cpu_usagemhz=589.00;; cpu_usage=6.90%;

but  display information  in nagios website when i use this command 
(No output on stdout) stderr: Can't locate Monitoring/Plugin/Functions.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/nagios/libexec/check_vmware_api.pl line 40.

**Comment by BaldMansMojo** [comment]
Read the readme (installation). You have to adjust the path.

**Comment by frayber** [comment]
I had the same problem, solved with 
yum install perl-Monitoring-Plugin

**Comment by BaldMansMojo** [comment]
Sorry - this is check_vmware_esx.pl - NOT check_vmware_api.pl. check_vmware_esx.pl is a fork of check_vmware_api.pl with cleaned up code, removed unneccesary parts. Read the history.. I had overseen that the first post was for the wrong plugin. check_vmware_esx.pl doesn't need the tthat perl module because the use of that module was incomplete and confusing in check_vmware_api.pl.

Regards- Martin

**Comment by frayber** [comment]
Yes you are right
