### ISSUE TITLE
cluster command

### ISSUE THREAD

**Issue by sRlinux** [BaldMansMojo/check_vmware_esx#113]
Can you please specify how to use cluster command? it always shows me the help page. Thanks for your advice.

**Comment by BaldMansMojo** [comment]
Look at the docs. It's mentioned that the cluster is not finished. This is because most of the checks of old plugin of op5 were simply nonsense (who needs the aggregated amount of CPU activity over a cluster to be checked). For resource groups etc. it makes sense but this wasn't implemented in the past and has to be done newly. And I hadn't enough time over the last months. Sorry. I'm working on some improvements at this time.
