### ISSUE TITLE
Critical! No result from CIM server.CIM server is probably not running or not running correctly! Please restart!

### ISSUE THREAD

**Issue by baaleal** [BaldMansMojo/check_vmware_esx#130]
Hi

We have the the next problem, the plugin get next info and the vm administrator answer us the CIM service is runnin ok.

/usr/lib64/nagios/plugins/check_vmware_esx -D 10.10.10.1 -f "/etc/nagios/objects/credential.cred" -S runtime -H esxsrv.local
Critical! No result from CIM server.CIM server is probably not running or not running correctly! Please restart!

![imagen](https://user-images.githubusercontent.com/16824012/33693105-6cb33e86-dab6-11e7-94a9-93cfb364a1a6.png)
![imagen](https://user-images.githubusercontent.com/16824012/33693123-8e90b4c0-dab6-11e7-8e93-de199012c397.png)

![imagen](https://user-images.githubusercontent.com/16824012/33692572-848c3466-dab3-11e7-8b49-4b7a3807919c.png)

![imagen](https://user-images.githubusercontent.com/16824012/33693006-ece76c04-dab5-11e7-8a55-8ee38b76720f.png)

Thanks for your help!

**Comment by BaldMansMojo** [comment]
We had that problem here too. CIM server reported running but when testing we found out that not all things were reported correctly. Restarting the CIM server fixed that problem. Therefore I put this message to the plugin.

Regards - Martin

**Comment by bb-Ricardo** [comment]
Hi,

We ran into the same problem with ESXi 6.5 hosts. Here was the issue that the health data in the CIM server output was set to undefined for some values.

That's why I added this commit: f530dd6963a0285e0d50dee7c1214b172d40ef77

BUT this also means you have to monitor your hardware separately through ILO/ILOM.

We especially had this issue with a HP DL580 G9. And botch ESXi images (vanilla vMware and HP custom image) had the same problem.

**Comment by BaldMansMojo** [comment]
Yep. We had it with Fujitsu Servers too. It was caused by the hardware agents Fujitsu deliverd for hardware information. We deinstalled the stuff and monitor the hardware now by management board.

Regards
Martin

**Comment by ant0nwax** [comment]
Good day

we have 10 ESXi 6.5 hosts at the moment and on 9 of them monitoring works with vmware_check_esx, on 1 there is one select and subselect that does not work.
ALL OF THESE 10 ESXI hosts DO NOT RUN CIM SERVER, still monitoring works on all of them, just not this one service:

root@monitoringsrv ~ # /usr/lib64/nagios/vmware/check_vmware_esx --host ch2-esxihost.subdomain.domain.tld --password [guesswhat] **--select runtime --subselect health** --sessionfiledir /var/spool/icinga2/tmp --sslport 443 --timeout 90 --username monitoring --trace=0
Critical! No result from CIM server.CIM server is probably not running or not running correctly! Please restart!


and if i start the sfcbd service, the hosts freezes :) need to unplug power from it :) even SOAP requests timeout then...
[root@esxihost:~] esxcli system wbem set --enable true
[root@esxihost:~] /etc/init.d/sfcbd-watchdog status
sfcbd is running
so this shall not run :) and it does not run on the other machines where it works

i know its not a bug in the monitoring script, just the error message is misleading since on the other hosts it does not show the error, monitoring is working, and CMI server is not running...

Happy for any thoughts and replies...

**Comment by bb-Ricardo** [comment]
Hi,

Yeah with 6.5 the health monitoring via VMWare is not the greatest to out it politely.

There should be a command option ‘—ignorehealth’ or so (please check the documentation to be sure) to avoid this issue. And yes I agree with you. A better error message would help a lot.

To monitor system health I could recommend my other project: https://github.com/bb-ricardo/check_redfish (currently tested with HP and Lenovo servers).
