### ISSUE TITLE
Full complete step-by-step guide for CentOS 7?

### ISSUE THREAD

**Issue by riahc3** [BaldMansMojo/check_vmware_esx#166]
Hello

The installation part of the guide is kind of flaky....Doesnt have that many details nor does it show commands that you have to run in order to get this plugin installed, more so for CentOS 7

Could that be updated and detailed a bit better?

Thank you

**Comment by BaldMansMojo** [comment]
Sorry - but his guide is a help for admins. Not a "How to install it in seven easy steps for dummies". You are the first one complaining about the docs. If you wanna have a "Installing check_vmware_esx for dummies" than write it. Nobody else seems to need it. And if the docs are to complicated for you I think it's not caused by the docs.
