### ISSUE TITLE
Uptime check / thresholds

### ISSUE THREAD

**Issue by GreyhoundHH** [BaldMansMojo/check_vmware_esx#38]
Hi,

the uptime check currently doesn't support thresholds. We've been using the check_vmware_api.pl with thresholds for uptime to handle alarming in case of unwanted reboots. Adapted to this script, we get an error:

check_vmware_esx.pl -D VCENTER -u USER -p PW -H HOST -S uptime -w 259200: -c 1800:
Warning threshold contains unwanted characters: 259200:

This format should be supported:
https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

Regards

**Comment by GreyhoundHH** [comment]
Hi Martin, is there any update on the Uptime-check in regards of detecting reboots?
Unfortunately this keeps me away from completely switching monitoring to this script.

**Comment by BaldMansMojo** [comment]
Nothing new. I haven't found anything. But as a workaround I recommend the following. I have done for a collegue. He's doing the check for Windows servers too.
- Enable SNMP
- Store the following as a shell script. In my scenario it is call check_uptime:

#!/bin/bash

#set -x
#
# Monitoring System Uptime with snmp

# M.Fuerstenau, Oce, 7.7.2010
# Changes:
#
# 07.07.2010 - Initial version


export SCRIPT_NAME=`basename $0`

# NoA = Number of arguments
export NoA=$#

# TSR = Time since reboot
export TSR=""

ffunction usage()
{

echo
echo "Usage: $SCRIPT_NAME [Options]"
echo 
echo "Options: -H <ip-address/hostname>"
echo "         -C <community>"
echo "         -t <If the uptime is smaller then this in minutes a system rebooted>"
echo " or"
echo "         -w <warning days> -c <critical days<"
echo "         -h for help"
echo
}

###############################################################
# --- MAIN - Hauptverarbeitung --------------------------------
###############################################################

if [ $NoA -eq 1 ] && [ $1 = "-h" ]
   then
   usage
   exit 0
fi

while getopts H:C:w:c:t:p:h OPTION
      do

      case "$OPTION"
           in
           H) HOST=$OPTARG ;;
           C) COMMUNITY=$OPTARG ;;
           t) TSR=$OPTARG ;;
           w) WARN=$OPTARG ;;
           c) CRIT=$OPTARG ;;
           p) PORT=$OPTARG ;;
           h) usage
              exit 0 ;;
          \?) echo
              echo "Invalid command arguments supplied"
              usage
              exit 3;;
      esac
      done

if [ $TSR ]
   then 
   if [ $WARN ] || [ $CRIT ]
      then 
      echo "Error: -t must not be used in conjunctions with -w or -c"
      usage
      exit 3
   fi
fi

if [ -e $HOST ] || [ $HOST = "-C" ] || [ $HOST = "-k" ]
   then 
   echo "Hostname or IP address not set!"
   usage
   exit 3
fi

if [ -e $COMMUNITY ]
   then
   echo "SNMP community string not set!"
   usage
   exit 3
fi

if [ -e $PORT ]
   then
   DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST .1.3.6.1.2.1.1.1.0 2>/dev/null)
   RETCO=$?
   else
   DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST:$PORT .1.3.6.1.2.1.1.1.0 2>/dev/null)
   RETCO=$?
fi
   

if [ $RETCO -ne 0 ]
   then
   for TRY in 1 2 3 4 5
       do
       if [ -e $PORT ]
          then
          DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST .1.3.6.1.2.1.1.1.0 2>/dev/null)
          RETCO=$?
          else
          DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST:$PORT .1.3.6.1.2.1.1.1.0 2>/dev/null)
          RETCO=$?
       fi
       if [ $RETCO -eq 0 ]
          then
          ITWORKS=0
          break
       else
          ITWORKS=1
       fi
       done
       
   if [ $ITWORKS -ne 0 ]
      then
      echo "Critical! SNMP is not accessible. Please check!"
      exit 2
   fi
fi

if [ -e $PORT ]
   then
   UPTIME=$(/usr/bin/snmpget -c $COMMUNITY -v1 $HOST .1.3.6.1.2.1.25.1.1.0 | sed 's/^.*(//' | sed 's/) */)/')
   else
   UPTIME=$(/usr/bin/snmpget -c $COMMUNITY -v1 $HOST:$PORT .1.3.6.1.2.1.25.1.1.0 | sed 's/^.*(//' | sed 's/) */)/')
fi

UPTIME_TICKS=$(echo $UPTIME | awk -F\) '{print $1}')
UPTIME=$(echo $UPTIME | awk -F\) '{print $2}' | sed 's/\..*$//')

if [ $TSR ]
   then
   # TSTR = Time since reboot ticks
   TSRT=$TSR
   (( TSRT = TSRT * 60 * 100 ))
   if [ $UPTIME_TICKS -lt $TSRT ]
      then
      echo "Critical! Uptime: $UPTIME - This is less than the given $TSR minutes. It looks like the system has rebooted."
      exit 2
   fi
   else

   if [ $WARN ] || [ $CRIT ]
      then
      if [ $WARN ]
         then
         (( WARNT = WARN * 24 * 60 * 60 * 100 ))
      fi

      if [ $CRIT ]
         then
         (( CRITT = CRIT * 24 * 60 * 60 * 100 ))
         if [ $UPTIME_TICKS -ge $CRITT ]
            then
            echo "Critical! Uptime: $UPTIME - This is more than the given $CRIT days."
            exit 2
         fi
         if [ $UPTIME_TICKS -ge $WARNT ]
            then
            echo "Warning! Uptime: $UPTIME - This is more than the given $WARN days."
            exit 1
         fi
      fi
      if [ $UPTIME_TICKS -ge $WARNT ]
         then
         echo "Warning! Uptime: $UPTIME - This is more than the given $WARN days."
         exit 2
      fi
   fi
fi

if [ $TSR ]
   then
   echo "Uptime: $UPTIME  - Time since reboot offset: $TSR minutes "
   else
   echo "Uptime: $UPTIME"
fi
exit 0

- Define a command:

define command {
               command_name          check_uptime_alert
               command_line  /usr/lib/nagios/ops_plugins/check_uptime -H $HOSTADDRESS$ -C $ARG1$ -t $ARG2$
               }

- Define a service for the relevant host:
define service{
       active_checks_enabled           1
       passive_checks_enabled          1
       parallelize_check               1
       obsess_over_service             1
       check_freshness                 0
       notifications_enabled           1
       event_handler_enabled           1
       flap_detection_enabled          1
       process_perf_data               0
       retain_status_information       1
       retain_nonstatus_information    1
        __TDSEVMAP                      critical=1 warning=2

       host_name                       myhostname
       service_description             Uptime
       is_volatile                     0
       check_period                    24x7
       max_check_attempts              1
       normal_check_interval           15
       retry_check_interval            1
       contact_groups                  my_vmware-admins
       notification_interval           1440
       notification_period             24x7
       notification_options            c,w,r
       check_command                   check_uptime_alert!mysnmpcommunity!20
}

The last value is the timer. If the updtime is less than 20 minutes you will have an alarm.

Best regards
Martin

**Comment by GreyhoundHH** [comment]
Hi,

unfortunately enabling SNMP and  storing local scripts on ESXi is not an option for us.
Is there any way to adapt the uptime-check (incl. thresholds) from check_vmware_api.pl? It works perfectly there…

Kind regards,
Daniel

Von: Martin Fuerstenau [mailto:notifications@github.com]
Gesendet: Freitag, 20. Februar 2015 23:02
An: BaldMansMojo/check_vmware_esx
Cc: Böttcher, Daniel
Betreff: Re: [check_vmware_esx] Uptime check / thresholds (#38)


Nothing new. I haven't found anything. But as a workaround I recommend the following. I have done for a collegue. He's doing the check for Windows servers too.

 *   Enable SNMP
 *   Store the following as a shell script. In my scenario it is call check_uptime:

#!/bin/bash

#set -x
#

Monitoring System Uptime with snmp
M.Fuerstenau, Oce, 7.7.2010
Changes:

#

07.07.2010 - Initial version

export SCRIPT_NAME=basename $0

NoA = Number of arguments

export NoA=$#

TSR = Time since reboot

export TSR=""

ffunction usage()
{

echo
echo "Usage: $SCRIPT_NAME [Options]"
echo
echo "Options: -H "
echo " -C "
echo " -t "
echo " or"
echo " -w -c <critical days<"
echo " -h for help"
echo
}

###############################################################

--- MAIN - Hauptverarbeitung --------------------------------

###############################################################

if [ $NoA -eq 1 ] && [ $1 = "-h" ]
then
usage
exit 0
fi

while getopts H:C:w:c:t:p:h OPTION
do

  case "$OPTION"

       in

       H) HOST=$OPTARG ;;

       C) COMMUNITY=$OPTARG ;;

       t) TSR=$OPTARG ;;

       w) WARN=$OPTARG ;;

       c) CRIT=$OPTARG ;;

       p) PORT=$OPTARG ;;

       h) usage

          exit 0 ;;

      \?) echo

          echo "Invalid command arguments supplied"

          usage

          exit 3;;

  esac

  done

if [ $TSR ]
then
if [ $WARN ] || [ $CRIT ]
then
echo "Error: -t must not be used in conjunctions with -w or -c"
usage
exit 3
fi
fi

if [ -e $HOST ] || [ $HOST = "-C" ] || [ $HOST = "-k" ]
then
echo "Hostname or IP address not set!"
usage
exit 3
fi

if [ -e $COMMUNITY ]
then
echo "SNMP community string not set!"
usage
exit 3
fi

if [ -e $PORT ]
then
DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST .1.3.6.1.2.1.1.1.0 2>/dev/null)
RETCO=$?
else
DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST:$PORT .1.3.6.1.2.1.1.1.0 2>/dev/null)
RETCO=$?
fi

if [ $RETCO -ne 0 ]
then
for TRY in 1 2 3 4 5
do
if [ -e $PORT ]
then
DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST .1.3.6.1.2.1.1.1.0 2>/dev/null)
RETCO=$?
else
DESCR=$(snmpget -c $COMMUNITY -v1 -r 30 -On $HOST:$PORT .1.3.6.1.2.1.1.1.0 2>/dev/null)
RETCO=$?
fi
if [ $RETCO -eq 0 ]
then
ITWORKS=0
break
else
ITWORKS=1
fi
done

if [ $ITWORKS -ne 0 ]
then
echo "Critical! SNMP is not accessible. Please check!"
exit 2
fi
fi

if [ -e $PORT ]
then
UPTIME=$(/usr/bin/snmpget -c $COMMUNITY -v1 $HOST .1.3.6.1.2.1.25.1.1.0 | sed 's/^.(//' | sed 's/) */)/')
else
UPTIME=$(/usr/bin/snmpget -c $COMMUNITY -v1 $HOST:$PORT .1.3.6.1.2.1.25.1.1.0 | sed 's/^.(//' | sed 's/) */)/')
fi

UPTIME_TICKS=$(echo $UPTIME | awk -F) '{print $1}')
UPTIME=$(echo $UPTIME | awk -F) '{print $2}' | sed 's/..*$//')

if [ $TSR ]
then
# TSTR = Time since reboot ticks
TSRT=$TSR
(( TSRT = TSRT * 60 * 100 ))
if [ $UPTIME_TICKS -lt $TSRT ]
then
echo "Critical! Uptime: $UPTIME - This is less than the given $TSR minutes. It looks like the system has rebooted."
exit 2
fi
else

if [ $WARN ] || [ $CRIT ]
then
if [ $WARN ]
then
(( WARNT = WARN * 24 * 60 * 60 * 100 ))
fi

  if [ $CRIT ]

     then

     (( CRITT = CRIT * 24 * 60 * 60 * 100 ))

     if [ $UPTIME_TICKS -ge $CRITT ]

        then

        echo "Critical! Uptime: $UPTIME - This is more than the given $CRIT days."

        exit 2

     fi

     if [ $UPTIME_TICKS -ge $WARNT ]

        then

        echo "Warning! Uptime: $UPTIME - This is more than the given $WARN days."

        exit 1

     fi

  fi

  if [ $UPTIME_TICKS -ge $WARNT ]

     then

     echo "Warning! Uptime: $UPTIME - This is more than the given $WARN days."

     exit 2

  fi

fi
fi

if [ $TSR ]
then
echo "Uptime: $UPTIME - Time since reboot offset: $TSR minutes "
else
echo "Uptime: $UPTIME"
fi
exit 0

 *   Define a command:

define command {
command_name check_uptime_alert
command_line /usr/lib/nagios/ops_plugins/check_uptime -H $HOSTADDRESS$ -C $ARG1$ -t $ARG2$
}

·         Define a service for the relevant host:
define service{
active_checks_enabled 1
passive_checks_enabled 1
parallelize_check 1
obsess_over_service 1
check_freshness 0
notifications_enabled 1
event_handler_enabled 1
flap_detection_enabled 1
process_perf_data 0
retain_status_information 1
retain_nonstatus_information 1
__TDSEVMAP critical=1 warning=2

host_name myhostname
service_description Uptime
is_volatile 0
check_period 24x7
max_check_attempts 1
normal_check_interval 15
retry_check_interval 1
contact_groups my_vmware-admins
notification_interval 1440
notification_period 24x7
notification_options c,w,r
check_command check_uptime_alert!mysnmpcommunity!20
}

The last value is the timer. If the updtime is less than 20 minutes you will have an alarm.

Best regards
Martin

**Comment by BaldMansMojo** [comment]
This is not a local script. It's a Nagios plugin. Enabling SNMP onVmware should be a must for some things linke monitoring network interface traffic. The data delivered by Vmware for interface traffic is kind a b...shit. We monitor her all interfaces via SNMP. You even got the status if an interface is up or down etc.

Martin

**Comment by GreyhoundHH** [comment]
Okay, but what about the Uptime-check from check_vmware_apli.pl? It runs fine and we’re not having any issues using it for > 2 years and it.
What’s wrong with the NIC-check via API? Link-detection works fine…

Daniel

Von: Martin Fuerstenau [mailto:notifications@github.com]
Gesendet: Montag, 23. Februar 2015 10:05
An: BaldMansMojo/check_vmware_esx
Cc: Böttcher, Daniel
Betreff: Re: [check_vmware_esx] Uptime check / thresholds (#38)


This is not a local script. It's a Nagios plugin. Enabling SNMP onVmware should be a must for some things linke monitoring network interface traffic. The data delivered by Vmware for interface traffic is kind a b...shit. We monitor her all interfaces via SNMP. You even got the status if an interface is up or down etc.

Martin

**Comment by BaldMansMojo** [comment]
ell - I had (unfortunately) not the time to look at it. For the interfaces I use an SNMP based plugin written by me. It is the same for Windows, Solaris, NetApp Filer, Vmware and Linux. All the same perfdata. That makes it for example easy to group corresponding interfaces from the filers and the VMware systems for reports.

Martin
