### ISSUE TITLE
Undefined subroutine &Vim

### ISSUE THREAD

**Issue by gitpumawit** [BaldMansMojo/check_vmware_esx#48]
Hi, 

When i try to use the tool, i have this error 
Undefined subroutine &Vim::unset_logout_on_disconnect called at ./check_vmware_esx.pl line 1749.
I run version 0.9.22

./check_vmware_esx.pl -H X.X.X.X -u nagios -p mypassword -S cpu 

what kind of infos did you need further?

Regards
marcel

**Comment by BaldMansMojo** [comment]
Hi,
sorry for the late answer but I was on vacation. Which version of the VMware Perl SDK do you use?

Regards
Martin

**Comment by gitpumawit** [comment]
Hola,
Thanks for the replay :-) 

SDK_(40_05.21.09)

Currently we have a lot of checks wieth check_esx3.pl and check_vmware.pl to check Vsphere Center.

Thanks for your great Support
marcel

**Comment by BaldMansMojo** [comment]
Where got you that version number? On my system a

pmvers VMware::VIRuntime
gives 
4.1
on my old test system. On my new gearman workers I have 5.5.
On both systems it works. This subroutine is part of VMware Perl SDK. So it should work. If it won't work you have a problem with the SDK. Maybe it is too old. If you are running Vmware prior to 5.x you should upgrade. ESX 4.x is out of support. My plugin won't completely run whith old ESX versions (4.x and older). op5 had a lot of depreciated performance counters in check_esx3.pl and check_vmware_api.pl. A lot of them is supported in new SDKs only for compatibility but will be kicked out. So I switched to 5.x for all counters and kicked out the old ones.
So check your SDK if it too old.
Kepp me informed.
Martin

**Comment by BaldMansMojo** [comment]
Got no answer since Jan 20. So I close this issue. If it is still valid please reopen.

Martin

**Comment by gitpumawit** [comment]
Sorry for my late answer. It works now. My version is now....

$ pmvers VMware::VIRuntime
5.5.0

Only to know, when i run the command in CLI all works.. but nagios show me on web 
 - Service check did not exit properly)

the soulution was to add on command.cfg  /usr/bin/perl in front of the command.

define command{
        command_name    check_esx
        command_line    /usr/bin/perl $USER1$/contrib/check_vmware_esx.pl -H $HOSTADDRESS$ -u $USER6$ -p $USER7$ $ARG1$
        }

Many Thanks
Great Work!

**Comment by BaldMansMojo** [comment]
You struggle with the old ePN (embedded Perl Nagios) problem. Nagios has an embedded Perl interpreter which is very limited. This is set to on by default. It can cause problems with a lot of plugins because it can't handle included modules (use module_name) correctly. Most people I know disable it.

In your nagios.cfg:
enable_embedded_perl=0
use_embedded_perl_implicitly=0
See in the docs
Advanced Topics -> Using the embedded Perl interpreter

Change it and reload your nagios.

Doing that you don't have to name the interpreter explicity.

Give me a short feedback it it works
Best regards
Martin

**Comment by gitpumawit** [comment]
Yes... it works for me too
