### ISSUE TITLE
Problem with Nagios plugin check_vmware_esx.pl

### ISSUE THREAD

**Issue by pochand** [BaldMansMojo/check_vmware_esx#50]
Hi,
I tried your plugin from Debian server shell and it works excellent.
I've a problem when try to use this in Nagios. (I use nagios 3 on
Debian 7 and the vmware server has esxi 5.1)
After define the command and service in this way:

define command{
command_name cpu_esxi
command_line $USER1$/check_vmware_esx_
master/check_vmware_esx.pl -H
$HOSTADDRESS$ -N 1-CUP -u $USER10$ -p $USER11$ -S cpu -s usage
}

define service{
use generic-service
hostname srv-voip
service_description CPU VM
check_command cpu_esxi!
}

where $USER1$ is the path /usr/lib/nagios/plugins

...after restarting service nagios3, the output of STATUS INFORMATION
on web interface is:
(Service check did not exit properly)

I tried to change the command define in this way:

define command{
command_name cpu_esxi
command_line /usr/bin/perl
$USER1$/check_vmware_esx_master/check_vmware_esx.pl -H $HOSTADDRESS$
-N 1-CUP -u $USER10$ -p $USER11$ -S cpu -s usage
}

now, the STATUS INFORMATION output is:
(null)

...I have read that another guy had the same problem but you
answered him that is a setup configuration problem and not plugin
problem. Can you help me?

Greeting
GD

**Comment by BaldMansMojo** [comment]
If it works from the command line the problem is normally your Nagios configuration. Here we have the following:
1) You tested as root but not as the user uder which nagios is running. Please check. Do always a su to the nagios user and test.
2) ePN (embedded Perl interpreter Nagios). I disable it normally because it causes problems with perl programs including other modules. In nagios.cfg I have
# EMBEDDED PERL INTERPRETER OPTION
# This option determines whether or not the embedded Perl interpreter
# will be enabled during runtime.  This option has no effect if Nagios
# has not been compiled with support for embedded Perl.
# Values: 0 = disable interpreter, 1 = enable interpreter

enable_embedded_perl=0



# EMBEDDED PERL USAGE OPTION
# This option determines whether or not Nagios will process Perl plugins
# and scripts with the embedded Perl interpreter if the plugins/scripts
# do not explicitly indicate whether or not it is okay to do so. Read
# the HTML documentation on the embedded Perl interpreter for more 
# information on how this option works.

use_embedded_perl_implicitly=0

That fixes most problems.

3) If set to executable you should not use the perl interpreter explicity. /usr/bin/perl scriptname can cause all options passed to the perl interpreter instead of the script.. As with shellscripts the first line of the script (#!/bin/bash for example) names the command interpreter to use.
4) If not passing arguments to a command you won't need a ! in the service command definition.
For debugging have a tail -f on the logfile and force the command check. You will see what happens.

Give me feedback if it works or not.

Best regards
Martin Fuerstenau

**Comment by pochand** [comment]
Nothing..I tried all but the status information answer is "(null)"..
I tried to simplify the command and to changhe the plugin directory to have all Nagios plugins in the same directory....but don't work..

root@nagios:/usr/lib/nagios/plugins# /usr/lib/nagios/plugins/check_vmware_esx.pl -H 192.168.104.90 -u root -p password -S cpu
CPU wait=19870.00 ms - CPU ready=7.00 ms - CPU usage=0.27%|'cpu_wait'=19870.00ms;;;; 'cpu_ready'=7.00ms;;;; 'cpu_usage'=0.27%;;;;

the SAME command from Nagios doesn't work.

define command{
command_name cpu_esxi
command_line $USER1$/check_vmware_esx.pl -H $HOSTADDRESS$ -u $USER10$ -p $USER11$ -S cpu
}

I also changed this line in the perl plugin:
#Own modules
use lib "/modules";
to 
#Own modules
use lib "./modules";

all involved file and directory has the wxr permission.

I will write you all information about my system:

root@nagios:~# perl -v
This is perl 5, version 14, subversion 2 (v5.14.2) built for i486-linux-gnu-thread-multi-64int

root@nagios:~# nagios3 -v
Nagios Core 3.4.1

root@nagios:~# uname -a
Linux nagios 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1 i686 GNU/Linux

**Comment by BaldMansMojo** [comment]
use lib "./modules";
I think this is the problem. Use the full path to your module directory. 

Why does ./modules works in test?
If you start the chek with ./check_vmware_esx.pl it is a correct pathname. But when used from Nagios it can be ?????? So test it with full path to the module directory. Should work.
Martin

**Comment by pochand** [comment]
it still doesn't work also changing the modules path into perl plugin..
have you other suggests? I finished the ideas.

**Comment by BaldMansMojo** [comment]
Stupid question - have you tested as the user running Nagios? According to the commandline prompt above you where root when tested it. 
Right?

**Comment by pochand** [comment]
I always use root. I start the daemon as root and so I edit the file. This is a server that I use only for Nagios and so I use only the root. It exists another user (debian) but I've never use it.

**Comment by BaldMansMojo** [comment]
Ok. What's in the Nagios log if you force a check?

**Comment by BaldMansMojo** [comment]
With one thing you can be absolutely sure - if it runs from the commandline you have a problem with Nagios and NOT with the plugin. 
Test it with hardcoded user and password instead of passing it via macros. Are you sure that there are no Unix/Linux reserved character in the userid or password? I've seen things like this with password containing a $ . In this case you have to masquerade it.

**Comment by pochand** [comment]
It works :D I'm happy..thank you very much....

**Comment by BaldMansMojo** [comment]
Just for my information - what was it?

**Comment by pochand** [comment]
the path of modules directory..
but  immediately after the correction and restart the service (I don't know why) doesn't work...after 15/20 minute it works :D

**Comment by BaldMansMojo** [comment]
You established a session when testing from the comment line. When disconnecting this session is stored in a file. When testing from Nagios you had a valid session (userid and password is only needed if no session exists) but a not working modules path. This corrupted the session. I think after 20 min the session was kicked of and nagios established a new one now with a valid module path.

Have a nice weekend.
Martin
