### ISSUE TITLE
500 read timeout

### ISSUE THREAD

**Issue by marcelfischer** [BaldMansMojo/check_vmware_esx#52]
Hello,

I try to monitor a new esxi 5.5 U2. But I get the following message:
time ./check_vmware_esx.pl -H 192.168.4.6 -u nagios -p XXX -S CPU -s usage --trace=100
SOAP request error - possibly a protocol issue: 500 read timeout
real    6m52.893s
user    0m0.257s
sys     0m0.027s

And I have quite high timeout values I think.
On ESXi side I see some messages like "User Nagios loged in as VI Perl".

I'm using VMware-vSphere-Perl-SDK-5.5.0-2043780

Do you have any Idea?
Thanks for your help!

**Comment by BaldMansMojo** [comment]
Hi,
first try to use the plugin? If yes please verify that you are able to connect to your vmware host. See https://pubs.vmware.com/vsphere-50/topic/com.vmware.ICbase/PDF/vsphere-esxi-vcenter-server-50-command-line-interface-getting-started-guide.pdf for the commandline tools. These tools are supplied with the Perl SDK.

If this works (I think it won't - see below) start with --nosession to avoid problems with the rights of the directory you will store the session files. But first check the session file directory for a session file. The name of the file contains the IP address of the vmware host.

As mentioned I think it won't work. The error message indicates a timeout. That means you have no valid connection/session. Perhaps this will help: 

https://communities.vmware.com/message/1324728
Verify that the user is created correctly:

https://pubs.vmware.com/vsphere-51/topic/com.vmware.vsphere.security.doc/GUID-670B9B8C-3810-4790-AC83-57142A9FE16F.html
http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1027647
http://blogs.vmware.com/kb/2011/08/getting-started-with-vsphere-5-creating-local-users-and-groups-in-esxi-50.html

Give a feedback please
Beside this: Do I know you from the OSMC in Nuremberg or so?

Best regards
Martin

**Comment by marcelfischer** [comment]
Hi Martin,

no I wasnt at OSMC... but I already openend some issue here ;)

I did some tests with esxcli and it works just fine.
#esxcli --server 192.168.4.6 --username nagios --password 'XXX' system time get
2015-03-22T18:19:49Z

I also tried an account with more privileges on check_vmware_esx like the root user, but this also didn't work... Also tried the --nosession but also nothing...

**Comment by marcelfischer** [comment]
The following resolved my problem
cpan install GAAS/libwww-perl-5.837.tar.gz

https://communities.vmware.com/message/2298661

**Comment by BaldMansMojo** [comment]
Fine. I normally never used the latest version of the SDK because this is only necessary when using new features of the ESX version. So because there is nothing new any 5.x version of the SDK will do the job.

Best regards
Martin

**Comment by morgajel** [comment]
So if I'm reading this correctly, this will impact newer setups like mine- I just migrated to vsphere 6 and loaded the vmware-vcli on a CentOS 7 host, and it looks like (by default) it won't work.  That said, the vmware-cmd command times out as well on CentOS 7:

vmware-cmd  --server vcenter.example.com -l -h esx1 --username vuser --password 'userpass'
SOAP request error - possibly a protocol issue: 500 read timeout

This tells me the problem is on the vmware side, and not something you can fix.  (I'm making this comment for future visitors to read).

**Comment by BaldMansMojo** [comment]
I reopened this issue as a result of the last comment. Thanks for it. We will have a test scenario with with vmware 6 within the next weeks. So I will test it. Stay tuned.
Meanwhile I will set up a new Nagios cluster with CentOS but I will use CentOS 6.x (latest release) to avoid additional trouble with systemd and other things like this. I think support up to 2020 (RHEL 6.x) should give us enough time to do one step after another.
Next week I will read the release notes for the differences between SDK 5 and SDK 6. But the plugin must be able to serve 5 and 6 because most of the installations (for the nest time) will be 5.
So again - stay tuned.
Martin

**Comment by morgajel** [comment]
@BaldMansMojo I've been documenting my progress here:
http://morgajel.net/2015/05/20/1676

it's.... not pleasant.

**Comment by BaldMansMojo** [comment]
Tried to install SDK 6 on CentOS 6.6. Nightmare. Back to the latest 5.5. Will also cause a lot of backported Perl RPM packages but not as much as 6.0. When I will replace my test Nagios server I will give it a second try.
