### ISSUE TITLE
HELP Getting "SOAP request error - possibly a protocol issue:"

### ISSUE THREAD

**Issue by talbaror** [BaldMansMojo/check_vmware_esx#75]
Hi ,

I Am using check_vmware_esx under ICINGA 2 on ESX 5.01 with following 
VMware-vSphere-Perl-SDK-6.0.0-2503617.x86_64 under Ubuntu 14.04 with 
 perl -MLWP -e 'print "$LWP::VERSION\n"';
5.837
and the issue is i keep getting on all checks for time to time following error 
"SOAP request error - possibly a protocol issue:"
Any idea how to solve it 
please advice
Thanks

**Comment by BaldMansMojo** [comment]
Don't use SDK 6.x . You don't need it for Vmware 5.x. Some people have reported trouble with SDK 6.x to me. I'm using an enterprise grade OS here (Red Hat clone CentOS), version 6.7. I wasn't able to get SDK 6.x to work even with the precompiled Perl modules. And Centos 7 is no option due to problems with systemd (ever tried to port some more complex init scripts to systemd?). But currently I have no Vmware 6.x installation. 2 month ago I talked with a Vware trainer. I told me "6.x for production? Never ever! Too early." 

So use
https://developercenter.vmware.com/web/sdk/55/vsphere-perl
Should work. I will close this issue. In case of trouble please reopen it.

Regards
Martin

**Comment by talbaror** [comment]
Thanks , works like charm
Cheers :-)

**Comment by talbaror** [comment]
Sorry , to soon to celebrate . i installed 5.5 as suggested but
after a while i get again "SOAP request error - possibly a protocol issue:"
and Error: A general system error occurred: SOAP session destroyed
any idea ?
Thanks

**Comment by BaldMansMojo** [comment]
Yep. I've seen it sometimes. The Perl SDK depends on libwww-perl. and SSL. Maybe this link can help you a little bit:
https://communities.vmware.com/message/2298661
To test it's best to use the command line tools from the SDK (see SDK documentation). If the connect from the CLI works well that plugin should work. Unfortunately I'm not an Ubuntu user.
Documentation can be found here:
https://www.vmware.com/support/developer/viperltoolkit/index.html
Read the installtion guide. There are some hints for Ubuntu (PDF page 12)

Regards
Martin

**Comment by BaldMansMojo** [comment]
Forgot one thing. Check the access rights for the directory to store the sessionfiles. The user running Nagios (or Icinga or Shinken or Naemon or...) must have access (rw) because the plugin is running with the user rights. Often someone tests it as root and when Nagios (running as user nagios) starts the plugin it won't work. For a test you can start it with --nosession (see command reference of my plugin). If this work you have a problem with the sessionfile directory.

Martin

**Comment by Steven-Harris-0** [comment]
Hi, Is there any update on this? I've tried the downgrades recommended for the net::HTTP and the lib-www perl, both without success.

**Comment by BaldMansMojo** [comment]
Without knowing anything about your landscape and can say anything about a solution.

**Comment by Steven-Harris-0** [comment]
Sorry, so this is occurring in vmware-vsphere-6.5.0-.noarch.rpm, CentOS 7, perl-libwww-perl-6.15.noarch.rpm

The exact error is this: "SOAP request error - possibly a protocol issue: read timeout", identical to the one above.

Thanks!

**Comment by BaldMansMojo** [comment]
Well - since few weeks I have 2 Nagios workers running CentOS 7 and therefore I can now proceed with the plugin. But back to your problem. What the heck is that a vmware rpm for? I have never seen it. You need the Perl SDK from https://my.vmware.com/group/vmware/get-download?downloadGroup=VS-PERL-SDK65. You can even test later versions like https://my.vmware.com/group/vmware/get-download?downloadGroup=VS-PERL-SDK67 but never older versions. From 6.x the SDK had more bugs than my old dog fleas.

For libwww-perl I'm using perl-libwww-perl-6.05-2.el7.noarch from CentOS repository.

So your 2 packages are absolutely unknown 2 me. When you install SDK by hand there is a question for installing some precompiled Perl modules. Say for installation of this modules
