### ISSUE TITLE
check_vmware_esx -S runtime -s health issues

### ISSUE THREAD

**Issue by jdufrene** [BaldMansMojo/check_vmware_esx#81]
Hello,
I monitor 4 ESXi 5.5 vith your plugin but I have an issue on 2 ESXi.
These two ESX are not on the same sub-network as the monitoring server, but there is any firewall rules between this two sub-network.
When I execute this command: ./check_vmware_esx -H IP -u login -p password -S runtime -s health
It returns: OK: All 4 health checks are GREEN: Storage (2x), CPU (2x) but there must be more than 4 health checks.
Let see the result on the others ESXi: OK: All 293 health checks are GREEN: System (11x), fan (7x), Slot/Connector (8x), CPU (2x), Cable/Interconnect (1x), Watchdog (5x), voltage (5x), Logging (2x), Processors (16x), Memory (101x), other (1x), Storage (85x), power (22x), Fan (3x), Power (8x), temperature (16x).
Please, do you know what are the causes of this issue?

**Comment by BaldMansMojo** [comment]
No. But it is not a problem of the plugin. OK:All4.... means that it gots only this 4 from server. It has nothing to with subnets or so. It maybe the are insuuficient rights for the user doing the check..

The output shows that everything works well. For debugging you can use perl data::dumper. 
So enable the dumper in check_vmware_esx.pl- It should be around line 1200 after 
$ENV{'PERL_LWP_SSL_VERIFY_HOSTNAME'} = 0; 

Here you enter
# Only for debugging
use Data::Dumper;
$Data::Dumper::Indent = 1;
#print "------------------------------------------\n" . Dumper ($store) . "\n" . "------------------------------------------\n";
 The print is just a sample for usage. 
if ( $@ )
   {

After that you open the module with an editor (should be host_runtime_info.pm) place the line above (uncommented) at the right place. Here it should be abfter line 83. It should looks like:

print "------------------------------------------\n" . Dumper ($host_view) . "\n" . "------------------------------------------\n";
Then test from the commandline.
I just remember (we had it in the past) that it may happen that the CIM provider ist not running correctly. Look at the CPU in the Vcenter. mostly here you will see inclomplete things. After restarting the CIM provider this should be fixed. Give me a feedback if it works so that we can close this issue

Regards - Martin

**Comment by jdufrene** [comment]
Thanks to reply.
I already try to restart the CIM server and it fixed the problem until now.
On one of the two servers, the check works just fine. But the other one return critical with this message: "Critical! No result from CIM server.CIM server is probably not running or not running correctly! Please restart!". I think that it isn't an issue from the plugin but from Vmware, but maybe you can help me to know what is wrong with the CIM server?

**Comment by BaldMansMojo** [comment]
the CIM server is buggy in some ESX 5.x versions. There were several updates. Which version do you use?

**Comment by jdufrene** [comment]
We used the 5.5 version.

**Comment by BaldMansMojo** [comment]
We too. The critical message you mentioned above was a wish of our Vmware admins. They get an alert and restart the CIM server. Sometimes several times. So I will close this issue now.

Good luck
Martin
