### ISSUE TITLE
Problems getting network usage from vSphere Version 6.0.0 Build 2997665

### ISSUE THREAD

**Issue by dongursli** [BaldMansMojo/check_vmware_esx#96]
I'm having problem getting some information when it comes to network usage from a specific VM. Running Nagios  4.1.1 on Red Hat 7.2
Using VMware-vSphere-Perl-SDK-6.0.0-3561779.x86_64 SDK

check_vmware_esx -D `<vCenter>` -N `<vm>` -u `<user>` -p `<password>-S` net -s usage
gives me: UNKNOWN: net usage=Not available
check_vmware_esx -D `<vCenter>` -N `<vm>` -u `<user>` -p `<password>` -S net
gives me: UNKNOWN: net usage=Not available net receive=Not available, net send=Not available

Have tested the original check_vmware_api.pl, same result.

rgds
Don

**Comment by BaldMansMojo** [comment]
As discussed in a lot of other issues: SDK 6.x has some bugs and some incompatibilities with SDK 5.x. You don't need 6.x because currently the plugin doesn't use new features from 6.x. Especially in an environment with VMware 5.x and 6.x SDK 6 will not work. So downgrade to the latest SDK 5.x

Regards
Martin

**Comment by dongursli** [comment]
I have tried with both VMware-vSphere-Perl-SDK-5.1.0-780721.x86_64 and VMware-vSphere-Perl-SDK-5.5.0-2043780.x86_64 same error from check_vmware_esx.

rgds
Don

**Comment by BaldMansMojo** [comment]
Sorry - I was a little bit toooo fast. Problem is not the plugin. Problem is yourVMware system. It simply delivers no data. The API devlivers nearly all data you can get using the web interface (because it uses it. Maybe you have a problem with your CIM provider. Restart it. I think you won't see any network data for this machine in the WebGui too.

But it is definetely a VMware problem.
Regards
Martin
